apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-auth-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shopmesh-prod

  source:
    repoURL: https://github.com/shopmesh/shopmesh-infra.git
    targetRevision: main
    path: charts/auth-service
    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
